# 阶段
stages:
  - install
  - build_prod
  - deploy_prod

# 缓存
cache:
  paths:
    - node_modules/

# 安装依赖
install:
  image: node:20.11.0
  stage: install
  tags:
    - weiqu
  only:
    refs:
      - master
    changes:
      - package.json
  before_script:
    - yarn config set registry https://registry.npmmirror.com/
    #Node.js 17 开始默认启用了 OpenSSL 3，而 OpenSSL 3 对于某些加密算法的支持方式与之前的版本有所不同
    - export NODE_OPTIONS=--openssl-legacy-provider 
  script: yarn

# 打包项目
build_prod:
  image: node:20.11.0
  stage: build_prod
  tags:
    - weiqu
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules/
  before_script:
    - yarn config set registry https://registry.npmmirror.com/
    #Node.js 17 开始默认启用了 OpenSSL 3，而 OpenSSL 3 对于某些加密算法的支持方式与之前的版本有所不同
    - export NODE_OPTIONS=--openssl-legacy-provider 
    - yarn install --frozen-lockfile
  script:
    - yarn build-prod
  artifacts:
    expire_in: 1 week
    paths:
      - .output/public/
  only:
    - master
  environment:
    name: prod

# 部署项目
deploy_prod:
  image: docker-hub.cuiqiu.com/weiqu/weiqu-server:2.5
  stage: deploy_prod
  tags:
    - weiqu
  only:
    - master
  script:
    - ls -a
    - /weiqu/coscli/coscli -i $QCLOUD8_COS_SECRET_ID -k $QCLOUD8_COS_SECRET_KEY -e cos.na-siliconvalley.myqcloud.com cp -r .output/public/ cos://lookup-dns-www-1330003253/
    - |
      curl -X POST "https://api.cloudflare.com/client/v4/zones/d12e325c74a15bb76bd543b1954895db/purge_cache" \
        -H "Authorization: Bearer $CLOUDFLARE1_CDN_REFRESH_API_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"files": ["https://lookup-dns.com/*"]}'
  environment:
    name: prod 