version: '3.2'
services:

  # yarn build-prod
  # yarn build-prod && docker-compose down && docker-compose up -d
  test_fe:
    hostname: web-server
    restart: always
    image: docker-hub.cuiqiu.com/weiqu/weiqu-nginx:1.25.3
    container_name: test_fe
    platform: linux/amd64
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/:/usr/share/nginx/html
      